[character]
success_symbol = "[â„µ](bold green)"
error_symbol = "[âš”](bold red)"

[directory]
truncation_symbol = "â€¦/"

[hostname]
ssh_only = false

[custom.ada]
files = ["alire.toml"]
when = "alr show"

symbol = "ğŸ "
command = "(&alr version)[0].Split()[-1]"
style = "green bold"

format = "via [$symbol($output)]($style)"
